const ROW_PER_PAGE = [10];
const ACTION_BLANK = '';
const ACTION_SHOW_USER_DETAIL = 'ACTION_SHOW_USER_DETAIL';
const ACTION_SHOW_USER_UPDATE = 'ACTION_SHOW_USER_UPDATE';
const ACTION_SHOW_CONFIRM_UPDATE = 'ACTION_SHOW_CONFIRM_UPDATE';
const NURSING_BASIC_INFO = {
    FORM_1: "1",
    FORM_2: "2",
    FORM_3: "3",
    FORM_4: "4",
}
const INSURANCE_TYPE = {
    MEDICAL_CARE: "医療",
    NURSING: "介護",
    MEDICAL_MENTAL: "医療(精神)"
}

export {
    ROW_PER_PAGE,
    ACTION_SHOW_USER_DETAIL,
    ACTION_SHOW_USER_UPDATE,
    ACTION_BLANK,
    ACTION_SHOW_CONFIRM_UPDATE,
    NURSING_BASIC_INFO,
    INSURANCE_TYPE
}